In [85]:
# importing libaries 
import pandas as pd
import numpy as np
import plotly as pt

# inspection 
df = pd.read_csv('../data/raw/Cannabis_Strains_Features.csv')
print(df.dtypes)
print(df.shape)

Strain          object
Type            object
Rating         float64
Effects         object
Flavor          object
Description     object
dtype: object
(2351, 6)

In [86]:
display(df.head())

,Strain,Type,Rating,Effects,Flavor,Description
0,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",$100 OG is a 50/50 hybrid strain that packs a ...
1,98-White-Widow,hybrid,4.7,"Relaxed,Aroused,Creative,Happy,Energetic","Flowery,Violet,Diesel",The ‘98 Aloha White Widow is an especially pot...
2,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...
3,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",13 Dawgs is a hybrid of G13 and Chemdawg genet...
4,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange","Also known as Kosher Tangie, 24k Gold is a 60%..."

In [87]:
##########CLEANING##########
#cleaning columns 
df_cleaned = df.copy()
df_cleaned.columns = [col.strip().lower() for col in df.columns]
df_cleaned.rename(columns={'strain': 'name'}, inplace=True)
display(df_cleaned.head())

,name,type,rating,effects,flavor,description
0,100-Og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",$100 OG is a 50/50 hybrid strain that packs a ...
1,98-White-Widow,hybrid,4.7,"Relaxed,Aroused,Creative,Happy,Energetic","Flowery,Violet,Diesel",The ‘98 Aloha White Widow is an especially pot...
2,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...
3,13-Dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",13 Dawgs is a hybrid of G13 and Chemdawg genet...
4,24K-Gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange","Also known as Kosher Tangie, 24k Gold is a 60%..."

In [88]:
# Check for duplicate rows
duplicate_rows = df[df.duplicated()]

# Display duplicate rows
print("Duplicate Rows:")
display(duplicate_rows)

Duplicate Rows:

,Strain,Type,Rating,Effects,Flavor,Description
151,B-Witched,hybrid,5.0,"Euphoric,Relaxed,Happy,Hungry,Sleepy","Earthy,Sweet,Citrus",B-Witched by Ocean Grown Seeds is a magical cr...

In [89]:
# drop duplicate rows
df_cleaned = df_cleaned.drop_duplicates()

In [90]:
# Check for null values in all columns
null_counts = df_cleaned.isnull().sum()
print("Null values in all columns:")
print(null_counts)

Null values in all columns:
name            0
type            0
rating          0
effects        29
flavor         44
description     5
dtype: int64

In [80]:
# Replace 0 with NaN in the 'rating' column
df_cleaned['rating'] = df_cleaned['rating'].replace(0, np.nan)

print("Null values in 'rating:' ",df_cleaned['rating'].isnull().sum())

Null values in 'rating:'  35

In [91]:
df_cleaned.dropna

<bound method DataFrame.dropna of                 name    type  rating  \
0             100-Og  hybrid     4.0
1     98-White-Widow  hybrid     4.7
2               1024  sativa     4.4
3           13-Dawgs  hybrid     4.2
4           24K-Gold  hybrid     4.6
...              ...     ...     ...
2346         Zeus-Og  hybrid     4.7
2347        Zkittlez  indica     4.6
2348     Zombie-Kush  indica     5.0
2349       Zombie-Og  indica     4.4
2350        Zoom-Pie  indica     4.6

                                         effects                     flavor  \
0     Creative,Energetic,Tingly,Euphoric,Relaxed        Earthy,Sweet,Citrus
1       Relaxed,Aroused,Creative,Happy,Energetic      Flowery,Violet,Diesel
2      Uplifted,Happy,Relaxed,Energetic,Creative    Spicy/Herbal,Sage,Woody
3        Tingly,Creative,Hungry,Relaxed,Uplifted  Apricot,Citrus,Grapefruit
4      Happy,Relaxed,Euphoric,Uplifted,Talkative       Citrus,Earthy,Orange
...                                          ...                        ...
2346   Happy,Uplifted,Relaxed,Euphoric,Energetic          Earthy,Woody,Pine
2347      Relaxed,Happy,Euphoric,Uplifted,Sleepy          Sweet,Berry,Grape
2348     Relaxed,Sleepy,Talkative,Euphoric,Happy  Earthy,Sweet,Spicy/Herbal
2349        Relaxed,Sleepy,Euphoric,Happy,Hungry       Sweet,Earthy,Pungent
2350        Hungry,Relaxed,Uplifted,Happy,Sleepy       Berry,Earthy,Pungent

                                            description
0     $100 OG is a 50/50 hybrid strain that packs a ...
1     The ‘98 Aloha White Widow is an especially pot...
2     1024 is a sativa-dominant hybrid bred in Spain...
3     13 Dawgs is a hybrid of G13 and Chemdawg genet...
4     Also known as Kosher Tangie, 24k Gold is a 60%...
...                                                 ...
2346  Zeus OG is a hybrid cross between Pineapple OG...
2347  Zkittlez is an indica-dominant mix of Grape Ap...
2348  Zombie Kush by Ripper Seeds comes from two dif...
2349  If you’re looking to transform into a flesh-ea...
2350  Zoom Pie (also known as Zombie Pie) is a heavy...

[2350 rows x 6 columns]>

In [92]:
#One-Hot Encoding
#one_hot_encoded = pd.get_dummies(df_cleaned['flavor'])
# Convert one-hot encoded DataFrame to numpy array if needed
#one_hot_encoded_array = one_hot_encoded.values

#display(one_hot_encoded)

In [94]:
df_cleaned['name'] = df_cleaned['name'].str.strip().str.lower()
display(df_cleaned)

,name,type,rating,effects,flavor,description
0,100-og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",$100 OG is a 50/50 hybrid strain that packs a ...
1,98-white-widow,hybrid,4.7,"Relaxed,Aroused,Creative,Happy,Energetic","Flowery,Violet,Diesel",The ‘98 Aloha White Widow is an especially pot...
2,1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...
3,13-dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",13 Dawgs is a hybrid of G13 and Chemdawg genet...
4,24k-gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange","Also known as Kosher Tangie, 24k Gold is a 60%..."
...,...,...,...,...,...,...
2346,zeus-og,hybrid,4.7,"Happy,Uplifted,Relaxed,Euphoric,Energetic","Earthy,Woody,Pine",Zeus OG is a hybrid cross between Pineapple OG...
2347,zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...
2348,zombie-kush,indica,5.0,"Relaxed,Sleepy,Talkative,Euphoric,Happy","Earthy,Sweet,Spicy/Herbal",Zombie Kush by Ripper Seeds comes from two dif...
2349,zombie-og,indica,4.4,"Relaxed,Sleepy,Euphoric,Happy,Hungry","Sweet,Earthy,Pungent",If you’re looking to transform into a flesh-ea...
2350,zoom-pie,indica,4.6,"Hungry,Relaxed,Uplifted,Happy,Sleepy","Berry,Earthy,Pungent",Zoom Pie (also known as Zombie Pie) is a heavy...

In [95]:
import requests
from bs4 import BeautifulSoup 
import pandas as pd

base_url = "https://www.zamnesia.com/35-cannabis-seeds/295-feminized-cannabis-seeds"
seed_names = []
seed_prices = []

# Headers to mimic a browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive"
}

# Use a session to handle cookies
session = requests.Session()

for page_number in range(1, 64):
    # Construct the URL for the current page
    url = f"{base_url}?p={page_number}&orderby=position&orderway=asc"

    response = session.get(url, headers=headers)

    if response.status_code == 200:
        # Get the HTML content as a string
        html_content = response.text

        # Create a BeautifulSoup object
        soup = BeautifulSoup(html_content, 'html.parser')

        # Find all parent containers with class 'right_side clearfix col-lg-9 col-md-8 col-sm-12 col-xs-12'
        parent_containers = soup.find_all('div', class_='right_side clearfix col-lg-9 col-md-8 col-sm-12 col-xs-12')

        for container in parent_containers:
            # Extract seed name
            name_element = container.find('a', class_='product_link')
            name = name_element.get('title').strip() if name_element else ''
            seed_names.append(name)

            # Extract seed price
            price_span = container.find('span', class_='price')
            if price_span:
                integer_part = price_span.find('span', class_='integer_part_of_price').text.strip().replace('.', '').replace(',', '') if price_span else None
                fractional_part = price_span.find('span', class_='fractial_part_of_price').text.strip() if price_span else None
                price_str = f"{integer_part}.{fractional_part}" if integer_part and fractional_part else ''
                price_str = price_str.replace('..', '.')
                # Convert price string to float
                try:
                    price = float(price_str.replace(',', '.'))
                except ValueError:
                    price = None  # Handle non-numeric prices
                
                seed_prices.append(price)

            else:
                seed_prices.append(None)

    else:
        print(f"Failed to retrieve the webpage for page {page_number}. Status code: {response.status_code}")

# Create a DataFrame
seed_df = pd.DataFrame({'Seed Name': seed_names, 'Price (€)': seed_prices})

# Display the DataFrame
display(seed_df)

                                         Seed Name  Price (€)
0       Amnesia Haze (Royal Queen Seeds) feminized      27.00
1                Cheese (Zamnesia Seeds) feminized      18.99
2            OG Kush (Royal Queen Seeds) feminized      21.50
3           White Widow (Zamnesia Seeds) feminized      18.99
4     Pineapple Kush (Royal Queen Seeds) feminized      25.00
...                                            ...        ...
8699            Super THC Pack - Feminized Strains      44.99
8700      Praise the Haze Pack - Feminized Strains      34.99
8701  Coffeeshop Classics Pack - Feminized Strains      59.99
8702        Terpene Dream Pack - Feminized Strains      54.99
8703      Papaya Cookies Auto (FastBuds) feminized      36.00

[8704 rows x 2 columns]

In [96]:
null_counts = seed_df.isnull().sum()
print("Null values in all columns:")
print(null_counts)

Null values in all columns:
Seed Name    0
Price (€)    2
dtype: int64

In [97]:
# Check for duplicate rows
duplicate_rows = seed_df[seed_df.duplicated()]

# Display duplicate rows
print("Duplicate Rows:")
display(duplicate_rows)

Duplicate Rows:

                                              Seed Name  Price (€)
24           Amnesia Haze (Royal Queen Seeds) feminized      27.00
25                    Cheese (Zamnesia Seeds) feminized      18.99
26                OG Kush (Royal Queen Seeds) feminized      21.50
27               White Widow (Zamnesia Seeds) feminized      18.99
28         Pineapple Kush (Royal Queen Seeds) feminized      25.00
...                                                 ...        ...
8683         Moby Delicious (Delicious Seeds) feminized      34.00
8684      Cotton Candy Kush (Delicious Seeds) feminized      22.00
8685       Lemon Gelato (Kannabia x Zamnesia) feminized      50.00
8686            Green Crack (Garden of Green) feminized      29.00
8687  Super Critical Bud CBD (Garden of Green) femin...      29.00

[7200 rows x 2 columns]

In [98]:
seed_df_cleaned = seed_df.copy()
seed_df_cleaned = seed_df_cleaned.drop_duplicates()
seed_df_cleaned.dropna
display(seed_df_cleaned)

                                         Seed Name  Price (€)
0       Amnesia Haze (Royal Queen Seeds) feminized      27.00
1                Cheese (Zamnesia Seeds) feminized      18.99
2            OG Kush (Royal Queen Seeds) feminized      21.50
3           White Widow (Zamnesia Seeds) feminized      18.99
4     Pineapple Kush (Royal Queen Seeds) feminized      25.00
...                                            ...        ...
8699            Super THC Pack - Feminized Strains      44.99
8700      Praise the Haze Pack - Feminized Strains      34.99
8701  Coffeeshop Classics Pack - Feminized Strains      59.99
8702        Terpene Dream Pack - Feminized Strains      54.99
8703      Papaya Cookies Auto (FastBuds) feminized      36.00

[1504 rows x 2 columns]

In [99]:
seed_df_cleaned.columns = [col.strip().lower().replace(" ", "_") for col in seed_df.columns]
seed_df_cleaned.rename(columns={'seed_name': 'name'}, inplace=True)
display(seed_df_cleaned)

                                              name  price_(€)
0       Amnesia Haze (Royal Queen Seeds) feminized      27.00
1                Cheese (Zamnesia Seeds) feminized      18.99
2            OG Kush (Royal Queen Seeds) feminized      21.50
3           White Widow (Zamnesia Seeds) feminized      18.99
4     Pineapple Kush (Royal Queen Seeds) feminized      25.00
...                                            ...        ...
8699            Super THC Pack - Feminized Strains      44.99
8700      Praise the Haze Pack - Feminized Strains      34.99
8701  Coffeeshop Classics Pack - Feminized Strains      59.99
8702        Terpene Dream Pack - Feminized Strains      54.99
8703      Papaya Cookies Auto (FastBuds) feminized      36.00

[1504 rows x 2 columns]

In [100]:
def clean_name(name):
    # Remove everything after "(" and " - " 
    name = name.split("(")[0].split(" - ")[0]
    name = name.replace(" auto", "")
    # Lowercase and strip the string
    return name.lower().strip()

# Apply the custom function to the "name" column
seed_df_cleaned["name"] = seed_df_cleaned["name"].apply(clean_name)
display(seed_df_cleaned)

                          name  price_(€)
0                 amnesia haze      27.00
1                       cheese      18.99
2                      og kush      21.50
3                  white widow      18.99
4               pineapple kush      25.00
...                        ...        ...
8699            super thc pack      44.99
8700      praise the haze pack      34.99
8701  coffeeshop classics pack      59.99
8702        terpene dream pack      54.99
8703       papaya cookies auto      36.00

[1504 rows x 2 columns]

In [101]:
#########JOIN#######
#set name as index
df_cleaned.set_index('name', inplace=True)
seed_df_cleaned.set_index('name', inplace=True)

display(df_cleaned)
display(seed_df_cleaned)

,type,rating,effects,flavor,description
name,,,,,
100-og,hybrid,4.0,"Creative,Energetic,Tingly,Euphoric,Relaxed","Earthy,Sweet,Citrus",$100 OG is a 50/50 hybrid strain that packs a ...
98-white-widow,hybrid,4.7,"Relaxed,Aroused,Creative,Happy,Energetic","Flowery,Violet,Diesel",The ‘98 Aloha White Widow is an especially pot...
1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...
13-dawgs,hybrid,4.2,"Tingly,Creative,Hungry,Relaxed,Uplifted","Apricot,Citrus,Grapefruit",13 Dawgs is a hybrid of G13 and Chemdawg genet...
24k-gold,hybrid,4.6,"Happy,Relaxed,Euphoric,Uplifted,Talkative","Citrus,Earthy,Orange","Also known as Kosher Tangie, 24k Gold is a 60%..."
...,...,...,...,...,...
zeus-og,hybrid,4.7,"Happy,Uplifted,Relaxed,Euphoric,Energetic","Earthy,Woody,Pine",Zeus OG is a hybrid cross between Pineapple OG...
zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...
zombie-kush,indica,5.0,"Relaxed,Sleepy,Talkative,Euphoric,Happy","Earthy,Sweet,Spicy/Herbal",Zombie Kush by Ripper Seeds comes from two dif...
zombie-og,indica,4.4,"Relaxed,Sleepy,Euphoric,Happy,Hungry","Sweet,Earthy,Pungent",If you’re looking to transform into a flesh-ea...
zoom-pie,indica,4.6,"Hungry,Relaxed,Uplifted,Happy,Sleepy","Berry,Earthy,Pungent",Zoom Pie (also known as Zombie Pie) is a heavy...

                          price_(€)
name
amnesia haze                  27.00
cheese                        18.99
og kush                       21.50
white widow                   18.99
pineapple kush                25.00
...                             ...
super thc pack                44.99
praise the haze pack          34.99
coffeeshop classics pack      59.99
terpene dream pack            54.99
papaya cookies auto           36.00

[1504 rows x 1 columns]

In [102]:
result = df_cleaned.join(seed_df_cleaned, how='inner')
display(result)

,type,rating,effects,flavor,description,price_(€)
name,,,,,,
1024,sativa,4.4,"Uplifted,Happy,Relaxed,Energetic,Creative","Spicy/Herbal,Sage,Woody",1024 is a sativa-dominant hybrid bred in Spain...,27.00
acid,hybrid,4.4,"Creative,Happy,Euphoric,Energetic,Uplifted","Lemon,Diesel,Earthy",Acid is Paradise Seeds’ take on the original N...,26.00
afghani,indica,4.3,"Relaxed,Sleepy,Happy,Euphoric,Hungry","Earthy,Sweet,Pine",Afghani is a heavy indica strain named after i...,19.99
afghani,indica,4.3,"Relaxed,Sleepy,Happy,Euphoric,Hungry","Earthy,Sweet,Pine",Afghani is a heavy indica strain named after i...,22.00
afgooey,indica,4.3,"Relaxed,Happy,Sleepy,Giggly,Uplifted","Woody,Pine,Pungent","Afgooey, also known as Afgoo, is a potent indi...",25.00
...,...,...,...,...,...,...
zamaldelica,sativa,4.5,"Tingly,Uplifted,Energetic","Mint,Sweet,Grapefruit",Zamaldelica by Ace Seeds is a potent sativa-do...,32.00
zen,hybrid,4.3,"Happy,Energetic,Uplifted,Euphoric,Focused","Earthy,Sweet,Flowery","With a balanced ratio of THC and CBD, Zen is t...",27.00
zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...,35.00
zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...,27.95
zkittlez,indica,4.6,"Relaxed,Happy,Euphoric,Uplifted,Sleepy","Sweet,Berry,Grape",Zkittlez is an indica-dominant mix of Grape Ap...,16.50